Buildlog analysis trigger
thoth-station/investigator pull request #393
Opened 2021-01-11 08:49 UTC by fridex

## Related Issues and Dependencies

Depends-On: https://github.com/thoth-station/messaging/pull/326
Depends-On: https://github.com/thoth-station/user-api/pull/1171

## This introduces a breaking change

- [x] No

## This Pull Request implements

… Explain your changes.

## Description

2021-01-11 08:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvestigator).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/investigator/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2021-01-12 13:15 UTC, fridex commented
Needs https://github.com/thoth-station/messaging/pull/330

2021-01-12 15:41 UTC, pacospace reviewed
One minor comment otherwise very good!! :100: Thanks!

2021-01-12 15:41 UTC, pacospace commented on thoth/investigator/build_analsysis_trigger/README.md
> +Thoth investigator schedules the following workflow to provide advice to user (human or bot):
description need to be updated

2021-01-12 15:42 UTC, fridex commented on thoth/investigator/build_analsysis_trigger/README.md
> +Thoth investigator schedules the following workflow to provide advice to user (human or bot):
:eyeglasses: adjusted :+1:

2021-01-12 15:44 UTC, pacospace approved these changes
:beer:  :motor_boat:

2021-01-12 15:44 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/investigator/pull/393#pullrequestreview-566406402" title="Approved">pacospace</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvestigator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/investigator/blob/master/OWNERS)~~ [pacospace]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-12 15:51 UTC, KPostOffice requested changes
`run_module("thoth.investigator.build_analysis_trigger.investigate_build_analysis_trigger")`

This line needs to be added to `consumer.py` otherwise the function won't be added to the handler lookup table

2021-01-12 15:53 UTC, KPostOffice commented
/hold

2021-01-12 15:53 UTC, fridex commented
Added. PTAL @KPostOffice

2021-01-12 16:41 UTC, KPostOffice commented
/unhold

2021-01-12 16:42 UTC, KPostOffice commented
/approve

2021-01-12 16:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/investigator/pull/393#issuecomment-758783534" title="Approved">KPostOffice</a>*, *<a href="https://github.com/thoth-station/investigator/pull/393#pullrequestreview-566406402" title="Approved">pacospace</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvestigator).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/investigator/blob/master/OWNERS)~~ [pacospace]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-12 16:43 UTC, pacospace commented
/retest

2021-01-12 16:51 UTC, pacospace commented
/retest

2021-01-12 17:00 UTC, pacospace commented
@harshad16 /retest not working?

2021-01-12 17:16 UTC, fridex commented
/retest
/help

2021-01-12 17:22 UTC, harshad16 commented
checking on the systems

2021-01-12 17:25 UTC, harshad16 commented
/retest

2021-01-12 17:34 UTC, harshad16 commented
This is a hostname issue, system is not able to get the result to Github.
working on it, will respond here , once i m able to fix this.

2021-01-12 17:51 UTC, harshad16 commented
It's back to business. thanks for all the patience

2021-01-12 17:51 UTC, fridex commented
> It's back to business. thanks for all the patience

Thanks! :+1:

2021-01-12 18:20 UTC, fridex commented
/retest

2021-01-12 18:36 UTC, merged