Internal trig advise user api
thoth-station/investigator pull request #616
Opened 2022-01-25 22:29 UTC by KPostOffice

## Related Issues and Dependencies

Make internal trigger advise requests from investigator because Kebechet no longer sends advise requests unless specifically requested
## This introduces a breaking change

- [ ] Yes
- [ ] No

## This Pull Request implements

… Explain your changes.

## Description

2022-01-25 22:29 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **pacospace** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @pacospace` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvestigator).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/investigator/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["pacospace"]} -->

2022-02-07 19:14 UTC, KPostOffice commented
Fixes: #622

2022-03-11 20:44 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | f0ece21fc98f95e4a08699277b7bab4ffc90fac5 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1502384848273149952) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-11 21:48 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | 0367cb6063891681867cc97879578887e63d23f5 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1502400865900695552) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-11 21:58 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | 39800e21042a6b3bbf41ca824afcc158856a50dd | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1502402768856420352) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-14 06:27 UTC, harshad16 reviewed
lgtm
is this tested ? will it be possible to be tested in test cluster?

2022-03-14 06:27 UTC, harshad16 commented
/deploy

2022-03-14 12:54 UTC, KPostOffice commented
@harshad16 Yeah, I tested this locally. Monitoring behavior in the test cluster is definitely a good idea as these are pretty large changes.

2022-03-17 10:25 UTC, codificat commented
Unsure why the mypy check is failing, but hoping that #635 might fix it

2022-03-17 10:59 UTC, harshad16 commented
/deploy

2022-03-17 11:00 UTC, harshad16 commented
> Yeah, I tested this locally. Monitoring behavior in the test cluster is definitely a good idea as these are pretty large changes.

ack, will get this in test

2022-06-21 18:46 UTC, KPostOffice commented
/remove-lifecycle stale

2022-06-23 19:52 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | b8aae11025b00519160df1d89c94e30de1179950 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1540060090004934656) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-28 19:27 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | 2ebb197d533ec3d6e83670d1d21901021280d409 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1541865875970199552) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-28 19:34 UTC, sesheta commented
@KPostOffice: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | 2ebb197d533ec3d6e83670d1d21901021280d409 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1541865875970199552) | true | `/test thoth-mypy-py38`
aicoe-ci/prow/pre-commit | 2ebb197d533ec3d6e83670d1d21901021280d409 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/pre-commit/1541865874779017216) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-30 09:53 UTC, codificat requested changes
There are some unresolved conflicts that slipped in...

2022-06-30 09:53 UTC, codificat commented on thoth/investigator/common.py
> +<<<<<<< HEAD
unresolved conflict

2022-06-30 09:53 UTC, codificat commented on thoth/investigator/hash_mismatch/investigate_hash_mismatch.py
> +<<<<<<< HEAD
unresolved conflict

2022-06-30 09:53 UTC, codificat commented on thoth/investigator/missing_package/investigate_missing_package.py
> +<<<<<<< HEAD
unresolved conflict

2022-06-30 09:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **kpostoffice** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Finvestigator).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/investigator/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kpostoffice"]} -->

2022-07-07 20:26 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | cd9097e7a17c2c5d2ce9d209f7747fd98c35143c | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1545142131599872000) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-07-07 20:31 UTC, sesheta commented
@KPostOffice: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/mypy | d5df8bbda077cdfa5f82fd74f524f2815656fdea | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_investigator/616/thoth-mypy-py38/1545143313919643649) | true | `/test thoth-mypy-py38`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=investigator&pr=616). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AKPostOffice). Please help us and [open an issue](https://github.com/thoth-station/investigator/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-04-26 19:13 UTC, closed without merging